services:
  - type: web
    name: anycubic-service-status
    runtime: node
    plan: free
    buildCommand: "echo \"No build step required\""
    startCommand: "npm start"
    healthCheckPath: /health
